### ISSUE TITLE
"Remote" extensions are not symlinked

### ISSUE THREAD

**Issue by Tummerhore** [cyberbiont/vscode-profiles#14]
I've installed the remote extensions for WSL, SSH, Containers and after activating the profiles extension I noticed that the mentioned remote extensions are not linked. Therefore, cloning the profile with these extensions does not copy them into the new profile.

**Comment by Tummerhore** [comment]
Just noticed that these extensions are explicitly ignored via the extension settings.

**Comment by cyberbiont** [comment]
Yeah, see the 'Write permission problem' chapter in Readme for the reasoning
