### ISSUE TITLE
Why symlinks

### ISSUE THREAD

**Issue by IrishBruse** [cyberbiont/vscode-profiles#5]
I was wondering why you use symlinks for the profiles it seems like a really bad approach as if you don't have admin access to the computer you cant use this plugin also wouldn't an easier way and one that is kind of the "official" way be to disable extensions and then only enable them based on the current profile having users need to reload the editor is not so much of an issue as well the profiles are kindof ment to be related to projects so you shouldn't really need to change profiles in the same project. This is just me being curious i havent looking into how you would implement it. My main reason for annoyance is that at collage the pcs don't retain anything so i have to install vscode from the beginning and i cant run admin stuff it also would just nicer to the users if they could just install the plugin and not have to mess with cli everytime love the extension though it works exactly how i wanted

**Comment by IrishBruse** [comment]
It could also make it so using vscode build in sync would work as all extensions are installed just disabled by default

**Comment by cyberbiont** [comment]
The reason is that VS Code API simply does not allow to manage enabled /  disabled extensions. Don't ask me why. This was my first thought when I devised the ways to implement profiles and it didn't work.

BTW, On Windows 10, you can create symlinks without admin rights if the developer mode is enabled on the machine. Though not sure if it will be of great help in your situation.

**Comment by IrishBruse** [comment]
![image](https://user-images.githubusercontent.com/14964651/129597849-7e6b6431-ee5d-4a9a-83e8-e32a89476bd2.png)
![image](https://user-images.githubusercontent.com/14964651/129597912-e850a184-904c-4e86-9cf8-0639ea9d4707.png)
They must have released it recently wonder if this could be of any use

**Comment by cyberbiont** [comment]
I doubt it. See [this thread](https://github.com/microsoft/vscode/issues/15466) 
It seems like disabling extension via API was never implemented.

**Comment by IrishBruse** [comment]
Ah crap never mind then ah well thanks for making the extensions its great for keeping vscode clean :)
